[build]
  [context.deploy-preview]
    ignore = "if [[ $HEAD == *feature/* ]]; then exit 1; else exit 0; fi"

[[redirects]]
  from = "/api/*"
  to = "https://score.snapshot.org/api/:splat"
  status = 200
  force = true

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"