import { getHelixLPSwapAddress } from 'utils/addressHelpers'
import { getBalanceNumber } from 'utils/formatBalance'

export const lpSwapAddress = getHelixLPSwapAddress()

export const ToolTipText = (lpTokenSymbol, lpTokenAmount, exTokenSymbol, exTokenAmount, isLiquidity=false) =>
!isLiquidity ? `The swap creator is offering yield genereated by ${getBalanceNumber(lpTokenAmount)} ${lpTokenSymbol} LP token and is asking for the yield generated by ${getBalanceNumber(exTokenAmount)} ${exTokenSymbol} LP tokens.`
:`The swap creator is offering ${getBalanceNumber(lpTokenAmount)} ${lpTokenSymbol} LP token and is asking for ${getBalanceNumber(exTokenAmount)} ${exTokenSymbol} LP tokens.`